-- app_chat.sql
CREATE DATABASE IF NOT EXISTS app_chat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE app_chat;

-- NGUOIDUNG
CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    maNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
    tenNguoiDung varchar(100) NOT NULL,
    anhDaiDien_URL VARCHAR(255) DEFAULT NULL,
    gioiTinh VARCHAR(10) DEFAULT NULL,
    ngaySinh DATE DEFAULT NULL,
    soDienThoai VARCHAR(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TAIKHOAN
CREATE TABLE IF NOT EXISTS TAIKHOAN (
    maTaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trangThai VARCHAR(50) DEFAULT 'offline',
    token VARCHAR(255) DEFAULT NULL,
    maNguoiDung INT,
    FOREIGN KEY (maNguoiDung) REFERENCES NGUOIDUNG(maNguoiDung)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PHONGCHAT
CREATE TABLE IF NOT EXISTS PHONGCHAT (
    maPhongChat INT AUTO_INCREMENT PRIMARY KEY,
    tenPhongChat VARCHAR(100) NOT NULL,
    loaiPhong TINYINT(1) DEFAULT 0,
    ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    maTaiKhoanTao INT,
    FOREIGN KEY (maTaiKhoanTao) REFERENCES TAIKHOAN(maTaiKhoan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- THANHVIEN_PHONG
CREATE TABLE IF NOT EXISTS THANHVIEN_PHONG (
    maPhongChat INT,
    maTaiKhoan INT,
    vaiTro VARCHAR(50) DEFAULT 'member',
    ngayThamGia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngayXoa TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (maPhongChat, maTaiKhoan),
    FOREIGN KEY (maPhongChat) REFERENCES PHONGCHAT(maPhongChat) ON DELETE CASCADE,
    FOREIGN KEY (maTaiKhoan) REFERENCES TAIKHOAN(maTaiKhoan) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TINNHAN
CREATE TABLE IF NOT EXISTS TINNHAN (
    maTinNhan INT AUTO_INCREMENT PRIMARY KEY,
    noiDung TEXT,
    duongDanFile VARCHAR(255) DEFAULT NULL,
    thoiGianGui TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    maTaiKhoanGui INT,
    maPhongChat INT,
    loaiTinNhan varchar(50) DEFAULT 'text',
    FOREIGN KEY (maTaiKhoanGui) REFERENCES TAIKHOAN(maTaiKhoan) ON DELETE SET NULL,
    FOREIGN KEY (maPhongChat) REFERENCES PHONGCHAT(maPhongChat) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TRANGTHAI_TINNHAN
CREATE TABLE IF NOT EXISTS TRANGTHAI_TINNHAN (
    maTinNhan INT,
    maTaiKhoan INT,
    trangThai VARCHAR(50) DEFAULT 'sent', -- sent, delivered, read
    thoiGianCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (maTinNhan, maTaiKhoan),
    FOREIGN KEY (maTinNhan) REFERENCES TINNHAN(maTinNhan) ON DELETE CASCADE,
    FOREIGN KEY (maTaiKhoan) REFERENCES TAIKHOAN(maTaiKhoan) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BANBE
CREATE TABLE IF NOT EXISTS BANBE (
    maTaiKhoan1 INT,
    maTaiKhoan2 INT,
    trangThai VARCHAR(50) DEFAULT 'cho', -- cho, dongy, tuchoi
    ngayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (maTaiKhoan1, maTaiKhoan2),
    FOREIGN KEY (maTaiKhoan1) REFERENCES TAIKHOAN(maTaiKhoan) ON DELETE CASCADE,
    FOREIGN KEY (maTaiKhoan2) REFERENCES TAIKHOAN(maTaiKhoan) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- INDEXES
CREATE INDEX idx_tinNhan_maPhongChat ON TINNHAN(maPhongChat);
CREATE INDEX idx_thanhVienPhong_maTaiKhoan ON THANHVIEN_PHONG(maTaiKhoan);