import logging
from pathlib import Path

import joblib
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger(__name__)

SAVED_MODEL_DIR = Path(__file__).resolve().parent / "saved_model"


def load_sample_dataset() -> pd.DataFrame:
    # Bộ câu tiếng Việt, nhân bản để có >500 câu (cân bằng clean/toxic)
    toxic_base = [
        "Tao ghét mày",
        "Mày ngu quá",
        "Câm đi",
        "Cút đi",
        "Đồ vô dụng",
        "Thằng khốn",
        "Đồ tồi",
        "Đồ đáng ghét",
        "Đồ hèn",
        "Tao sẽ đánh mày",
        "Mày thật thảm hại",
        "Đồ thất bại",
        "Đồ bẩn thỉu",
        "Đồ rác rưởi",
        "Mày không ra gì",
        "Biến khỏi đây",
        "Cút xéo",
        "Đừng xuất hiện nữa",
        "Mày đáng bị phạt",
        "Đồ phản bội",
        "Đồ lừa đảo",
        "Đồ hâm",
        "Đồ điên",
        "Đồ thần kinh",
        "Đồ mất dạy",
        "Mày tệ hại",
        "Mày đáng khinh",
        "Tao muốn hạ gục mày",
        "Đồ giả dối",
        "Tao sẽ phá hỏng mày",
        "Đồ khốn nạn",
        "Đồ vô học",
        "Đồ bất tài",
        "Đồ mất nết",
        "Tao muốn đấm mày",
        "Mày là tai họa",
        "Đồ xấu xa",
        "Mày là gánh nặng",
        "Mày nên biến mất",
        "Đồ đạo đức giả",
        "Đồ nhát gan",
        "Đồ ngu si",
        "Đồ lố bịch",
        "Đồ đáng sợ",
        "Đồ quái vật",
        "Đồ vô liêm sỉ",
        "Đồ thô lỗ",
        "Đồ mất lịch sự",
        "Tao ghét nhìn thấy mày",
        "Đồ vô cảm",
        "Đồ láo toét",
        "Đồ điêu",
        "Đồ cặn bã",
        "Đồ lười biếng",
        "Đồ dối trá",
        "Đồ vô trách nhiệm",
        "Đồ hổ lốn",
        "Đồ tệ hại",
        "Đồ kém cỏi",
        "Đồ ngu ngốc",
        "Đồ đáng nguyền rủa",
        "Đồ tồi tệ",
        "Đồ dở hơi",
        "Đồ thất đức",
        "Đồ đê tiện",
        "Đồ bỉ ổi",
        "Đồ xấu tính",
        "Đồ hư hỏng",
        "Đồ lăng mạ",
        "Đồ xấc xược",
        "Đồ phá hoại",
        "Đồ chướng tai",
        "Đồ phiền phức",
        "Đồ bạo lực",
        "Đồ tàn nhẫn",
        "Đồ độc ác",
        "Đồ hung hãn",
        "Đồ thù ghét",
        "Đồ nhục mạ",
        "Đồ xúc phạm",
        "Đồ bủn xỉn",
        "Đồ ích kỷ",
        "Đồ tham lam",
        "Đồ lừa dối",
        "Đồ bịa đặt",
        "Đồ trơ tráo",
        "Đồ gian xảo",
        "Đồ khinh người",
        "Đồ coi thường người khác",
        "Đồ khốn",
        "Đồ phá đám",
        "Đồ hằn học",
        "Đồ bốc đồng",
        "Đồ cục súc",
        "Đồ bất lịch sự",
        "Đồ khốn kiếp",
        "Đồ khốn cùng",
        "Đồ đá đểu",
        "Đồ cay nghiệt",
        "Đồ ghen tị",
        "Đồ hẹp hòi",
        "Đồ ác độc",
        "Đồ tệ bạc",
        "Đồ hắc ám",
        "Đồ vô đạo đức",
        "Đồ xạo sự",
        "Đồ tào lao",
        "Đồ dơ dáy",
        "Đồ hư danh",
        "Đồ giả tạo",
        "Đồ phán xét",
        "Đồ dở người",
        "Đồ điêu ngoa",
        "Đồ quậy phá",
        "Đồ đê hèn",
        "Đồ đáng tởm",
        "Đồ hỗn láo",
        "Đồ trịch thượng",
        "Đồ ác ý",
        "Đồ thất lễ",
        "Đồ thô tục",
        "Đồ vô lễ",
        "Đồ nịnh hót",
        "Đồ bất công",
        "Đồ vô cảm xúc",
        "Đồ giả nhân",
        "Đồ đê tiện",
        "Đồ phản diện",
        "Đồ lố",
        "Đồ hợm hĩnh",
        "Đồ phản cảm",
        "Đồ bẩn",
        "Đồ đáng ghét thật sự",
        "Đồ nghiệt ngã",
        "Đồ ghê tởm",
        "Đồ lố lăng",
        "Đồ bủn xỉn",
        "Đồ nhục nhã",
        "Đồ thù địch",
        "Đồ ghét bỏ",
        "Đồ chanh chua",
        "Đồ ghê gớm",
        "Đồ đanh đá",
        "Đồ mất nết quá",
        "Đồ khốn khổ",
        "Đồ chọc tức",
        "Đồ khó ưa",
        "Đồ tồi tàn",
        "Đồ độc hại",
        "Đồ đáng xấu hổ",
        "Đồ cay độc",
        "Đồ hiểm độc",
        "Đồ đáng ghét vô cùng",
        "Đồ bẩn thỉu kinh tởm",
    ]

    clean_base = [
        "Chúc bạn một ngày tốt lành",
        "Cảm ơn bạn rất nhiều",
        "Bạn làm tốt lắm",
        "Thật tuyệt vời",
        "Chúng ta cùng cố gắng",
        "Rất vui được gặp bạn",
        "Chúc mừng sinh nhật",
        "Chúc ngủ ngon",
        "Chúc may mắn",
        "Chúc sức khỏe",
        "Bạn thật tử tế",
        "Bạn thật tuyệt",
        "Bạn thật dễ thương",
        "Bạn là người bạn tốt",
        "Bạn rất thông minh",
        "Bạn rất sáng tạo",
        "Bạn rất nhiệt tình",
        "Bạn rất chu đáo",
        "Bạn rất hào phóng",
        "Bạn rất tận tâm",
        "Tôi rất trân trọng bạn",
        "Tôi rất cảm kích",
        "Tôi rất biết ơn",
        "Tôi rất vui",
        "Tôi rất hạnh phúc",
        "Thật là một ý tưởng hay",
        "Thật là một ngày đẹp trời",
        "Thật là một trải nghiệm tốt",
        "Cùng nhau hợp tác nhé",
        "Chúng ta làm được",
        "Cố lên, bạn làm được",
        "Tuyệt vời ông mặt trời",
        "Rất tuyệt",
        "Rất ổn",
        "Quá ổn",
        "Ổn áp",
        "Chuẩn luôn",
        "Chuẩn bài",
        "Hết sảy",
        "Xuất sắc",
        "Ngon lành",
        "Lành mạnh",
        "Thân thiện",
        "Tốt bụng",
        "Dễ mến",
        "Lịch sự",
        "Tôn trọng",
        "Vui vẻ",
        "Thoải mái",
        "Hòa nhã",
        "Nhẹ nhàng",
        "Ân cần",
        "Quan tâm",
        "Chia sẻ",
        "Cởi mở",
        "Ủng hộ",
        "Khích lệ",
        "Động viên",
        "Tươi sáng",
        "Tích cực",
        "Lạc quan",
        "Tin tưởng",
        "Hy vọng",
        "An toàn",
        "Bình an",
        "Hạnh phúc",
        "Vững vàng",
        "Tự tin",
        "Yêu đời",
        "Yêu thương",
        "Đoàn kết",
        "Chung sức",
        "Chung lòng",
        "Nhiệt huyết",
        "Hào hứng",
        "Hứng khởi",
        "Hân hoan",
        "Hòa bình",
        "Chân thành",
        "Trung thực",
        "Công bằng",
        "Thấu hiểu",
        "Đồng cảm",
        "Bao dung",
        "Vị tha",
        "Âm áp",
        "Ấm cúng",
        "Vui tươi",
        "Dễ chịu",
        "Thư giãn",
        "Bình tĩnh",
        "Hiền hòa",
        "Thân thiện vô cùng",
        "Yêu thích",
        "Rất thích",
        "Rất yêu",
        "Rất quý",
        "Rất mến",
        "Rất kính trọng",
        "Rất nể phục",
        "Rất tự hào",
        "Rất biết ơn",
        "Rất hài lòng",
        "Rất mãn nguyện",
        "Rất vui vẻ",
        "Rất ấm áp",
        "Rất tuyệt vời",
        "Rất sung sướng",
        "Rất phấn khởi",
        "Rất hào hứng",
        "Rất tích cực",
        "Rất lạc quan",
        "Rất khỏe mạnh",
        "Rất an tâm",
        "Rất yên tâm",
        "Rất thoải mái",
        "Rất nhẹ nhàng",
        "Rất ân cần",
        "Rất chu đáo",
        "Rất quan tâm",
        "Rất ủng hộ",
        "Rất khích lệ",
        "Rất động viên",
        "Rất thân thiện",
        "Rất hiền lành",
        "Rất lịch thiệp",
        "Rất nghiêm túc",
        "Rất tử tế",
        "Rất hòa nhã",
        "Rất chân thành",
        "Rất trung thực",
        "Rất công bằng",
        "Rất thấu hiểu",
        "Rất đồng cảm",
        "Rất bao dung",
        "Rất vị tha",
        "Rất đoàn kết",
        "Rất yêu thương",
        "Rất gắn bó",
        "Rất nhiệt huyết",
        "Rất hòa bình",
        "Rất an nhiên",
        "Rất an lạc",
        "Rất trong lành",
        "Rất tươi mới",
        "Rất hứng khởi",
        "Rất vui tươi",
        "Rất thân ái",
        "Rất chan hòa",
        "Rất tin tưởng",
        "Rất hy vọng",
        "Rất khích lệ nhau",
        "Rất hỗ trợ nhau",
        "Cố gắng cùng nhau",
        "Đồng hành cùng nhau",
        "Chung tay cùng nhau",
        "Phối hợp nhịp nhàng",
        "Làm việc nhóm tốt",
        "Tôn trọng lẫn nhau",
        "Lắng nghe nhau",
        "Chia sẻ với nhau",
        "Giúp đỡ nhau",
        "Động viên nhau",
        "Khích lệ nhau",
        "Tin tưởng nhau",
        "Bảo vệ nhau",
        "Nâng đỡ nhau",
        "Cùng nhau tiến bộ",
        "Cùng nhau phát triển",
        "Cùng nhau thành công",
        "Cùng nhau vui vẻ",
        "Cùng nhau hạnh phúc",
    ]

    toxic = [f"{s} {i}" for i in range(1, 10) for s in toxic_base]
    clean = [f"{s} {i}" for i in range(1, 10) for s in clean_base]

    samples = [(t, 1) for t in toxic] + [(c, 0) for c in clean]
    logger.info("Synthetic Vietnamese dataset size: %d", len(samples))
    return pd.DataFrame(samples, columns=["text", "label"])


def train_and_save() -> None:
    df = load_sample_dataset()
    logger.info("Loaded dataset with %d rows", len(df))

    X_train, X_test, y_train, y_test = train_test_split(
        df["text"], df["label"], test_size=0.2, random_state=42, stratify=df["label"]
    )

    pipeline = Pipeline(
        [
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1)),
            ("clf", LogisticRegression(max_iter=200, n_jobs=1)),
        ]
    )

    pipeline.fit(X_train, y_train)
    logger.info("Model trained")

    y_pred = pipeline.predict(X_test)
    report = classification_report(y_test, y_pred)
    logger.info("\n%s", report)

    SAVED_MODEL_DIR.mkdir(parents=True, exist_ok=True)
    vectorizer: TfidfVectorizer = pipeline.named_steps["tfidf"]
    classifier: LogisticRegression = pipeline.named_steps["clf"]

    joblib.dump(vectorizer, SAVED_MODEL_DIR / "vectorizer.pkl")
    joblib.dump(classifier, SAVED_MODEL_DIR / "model.pkl")
    logger.info("Artifacts saved to %s", SAVED_MODEL_DIR)


if __name__ == "__main__":
    train_and_save()
